kube-prometheus-stack:
  grafana:
    enabled: true
    ingress:
        enabled: false
    route:
      main:
        enabled: true
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        hostnames:
          - grafana.llm.platform
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: eg
            namespace: envoy-gateway-system
        matches:
          - path:
              type: PathPrefix
              value: /

  alertmanager:
    enabled: false

  prometheus:
    prometheusSpec:
      retention: 3d
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
    ingress:
      enabled: false
    route:
      main:
        enabled: true
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        hostnames:
          - prometheus.llm.platform
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: eg
            namespace: envoy-gateway-system
        matches:
          - path:
              type: PathPrefix
              value: /

  kubeEtcd:
    enabled: false

  kubeScheduler:
    enabled: false

  kubeControllerManager:
    enabled: false
