# -----------------------------------------------------------------------------
# kserve-resources
# -----------------------------------------------------------------------------
kserve-resources:
  kserve:
    controller:
      deploymentMode: Standard

      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 250m
          memory: 512Mi

      gateway:
        domain: inference.llm.platform
        domainTemplate: "{{ .Name }}.{{ .IngressDomain }}"
        urlScheme: http
        ingressGateway:
          enableGatewayApi: true
          gateway: envoy-gateway-system/eg
          className: eg
          kserveGateway: envoy-gateway-system/eg

# -----------------------------------------------------------------------------
# kserve-llmisvc-resources
# -----------------------------------------------------------------------------
kserve-llmisvc-resources:
  kserve:
    llmisvc:
      controller:
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 512Mi
