apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inference-model
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: 'https://github.com/milinddethe15/llm-inference-platform.git'
    targetRevision: main
    path: platform/inference-model
  destination:
    server: https://kubernetes.default.svc
    namespace: kserve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
